#pragma once
#include <core_net/vm/opcodes_def.hpp>
#include <core_net/vm/variant.hpp>

#include <map>

namespace core_net { namespace vm {
   enum opcodes {
      CORE_NET_VM_CONTROL_FLOW_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_BR_TABLE_OP(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_RETURN_OP(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_CALL_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_CALL_IMM_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_PARAMETRIC_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_VARIABLE_ACCESS_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_MEMORY_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_I32_CONSTANT_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_I64_CONSTANT_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_F32_CONSTANT_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_F64_CONSTANT_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_COMPARISON_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_NUMERIC_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_CONVERSION_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_EXIT_OP(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_EMPTY_OPS(CORE_NET_VM_CREATE_ENUM)
      CORE_NET_VM_ERROR_OPS(CORE_NET_VM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         CORE_NET_VM_CONTROL_FLOW_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_BR_TABLE_OP(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_RETURN_OP(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_CALL_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_CALL_IMM_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_PARAMETRIC_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_VARIABLE_ACCESS_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_MEMORY_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_I32_CONSTANT_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_I64_CONSTANT_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_F32_CONSTANT_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_F64_CONSTANT_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_COMPARISON_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_NUMERIC_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_CONVERSION_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_EXIT_OP(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_EMPTY_OPS(CORE_NET_VM_CREATE_MAP)
         CORE_NET_VM_ERROR_OPS(CORE_NET_VM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   CORE_NET_VM_CONTROL_FLOW_OPS(CORE_NET_VM_CREATE_CONTROL_FLOW_TYPES)
   CORE_NET_VM_BR_TABLE_OP(CORE_NET_VM_CREATE_BR_TABLE_TYPE)
   CORE_NET_VM_RETURN_OP(CORE_NET_VM_CREATE_CONTROL_FLOW_TYPES)
   CORE_NET_VM_CALL_OPS(CORE_NET_VM_CREATE_CALL_TYPES)
   CORE_NET_VM_CALL_IMM_OPS(CORE_NET_VM_CREATE_CALL_IMM_TYPES)
   CORE_NET_VM_PARAMETRIC_OPS(CORE_NET_VM_CREATE_TYPES)
   CORE_NET_VM_VARIABLE_ACCESS_OPS(CORE_NET_VM_CREATE_VARIABLE_ACCESS_TYPES)
   CORE_NET_VM_MEMORY_OPS(CORE_NET_VM_CREATE_MEMORY_TYPES)
   CORE_NET_VM_I32_CONSTANT_OPS(CORE_NET_VM_CREATE_I32_CONSTANT_TYPE)
   CORE_NET_VM_I64_CONSTANT_OPS(CORE_NET_VM_CREATE_I64_CONSTANT_TYPE)
   CORE_NET_VM_F32_CONSTANT_OPS(CORE_NET_VM_CREATE_F32_CONSTANT_TYPE)
   CORE_NET_VM_F64_CONSTANT_OPS(CORE_NET_VM_CREATE_F64_CONSTANT_TYPE)
   CORE_NET_VM_COMPARISON_OPS(CORE_NET_VM_CREATE_TYPES)
   CORE_NET_VM_NUMERIC_OPS(CORE_NET_VM_CREATE_TYPES)
   CORE_NET_VM_CONVERSION_OPS(CORE_NET_VM_CREATE_TYPES)
   CORE_NET_VM_EXIT_OP(CORE_NET_VM_CREATE_EXIT_TYPE)
   CORE_NET_VM_EMPTY_OPS(CORE_NET_VM_CREATE_TYPES)
   CORE_NET_VM_ERROR_OPS(CORE_NET_VM_CREATE_TYPES)

   using opcode = variant<
      CORE_NET_VM_CONTROL_FLOW_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_BR_TABLE_OP(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_RETURN_OP(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_CALL_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_CALL_IMM_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_PARAMETRIC_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_VARIABLE_ACCESS_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_MEMORY_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_I32_CONSTANT_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_I64_CONSTANT_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_F32_CONSTANT_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_F64_CONSTANT_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_COMPARISON_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_NUMERIC_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_CONVERSION_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_EXIT_OP(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_EMPTY_OPS(CORE_NET_VM_IDENTITY)
      CORE_NET_VM_ERROR_OPS(CORE_NET_VM_IDENTITY_END)
      >;
}} // namespace core_net::vm
